version: '3.9'
services:
  mongodb_bug_report:
    container_name: mongodb_bug_report_container
    image: mongo
    ports:
      - 17000:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234