version: '3.9'
services:
  mongodb_bug_report:
    container_name: mongodb_bug_report_container
    image: mongo:latest
    restart: always
    volumes:
      - ./mongo_db:/data/db/
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${DB_NAME}