name: CI

on:
  push: 
    branches: [ main ]
  
  workflow_dispatch: 
  
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: 18.x
        
      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ". , !node_modules"
          target: "/bug_report"
          
      - name : Update API
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: 
            cd /home/tutilabs/bug_report/bug_report_backend && docker-compose up -d         
          
          
          
          
